// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'main': string;
  'paper': string;
  'sliderContainer': string;
}
declare var cssExports: CssExports;
export = cssExports;
